services:
  yolo-auto:
    image: registry.cn-hangzhou.aliyuncs.com/daxx/yolo-auto-container:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: yolo-auto
    restart: unless-stopped
    ports:
      - "2222:2222"
    gpus: all
    volumes:
      - datasets:/workspace/datasets
      - jobs:/workspace/jobs
      - models:/workspace/models
      - /root/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro

volumes:
  jobs:
    driver: local
  datasets:
    driver: local
  models:
    driver: local
