services:
  yolo-auto:
    image: registry.cn-hangzhou.aliyuncs.com/daxx/yolo-auto-container:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: yolo-auto
    restart: unless-stopped
    ports:
      - "2222:2222"
    environment:
      # MLflow tracking backend used by yolo-auto
      MLFLOW_TRACKING_URI: "sqlite:////workspace/mlflow.db"
    gpus: all
    volumes:
      - /data/yolo-datasets:/workspace/datasets
      - /data/yolo-jobs:/workspace/jobs
      - /data/yolo-models:/workspace/models
      - /root/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro
      - ./mc-config.json:/root/.mc/config.json:ro